export const data = [{
    school: 'soet',
    branch: 'btech',
    batch: '2023',
    paymentId: 'PAY12345',
    regNo: 'REG001',
    semFees: '50000',
    regFees: '5000',
    fine: '0',
    paymentMode: 'online',
    chequeNo: '',
    transactionId: 'TXN98765',
    bankName: 'HDFC',
    status: 'completed',
  },
  {
    school: 'som',
    branch: 'mba',
    batch: '2024',
    paymentId: 'PAY12346',
    regNo: 'REG002',
    semFees: '70000',
    regFees: '6000',
    fine: '1000',
    paymentMode: 'cheque',
    chequeNo: 'CHQ12345',
    transactionId: '',
    bankName: 'SBI',
    status: 'pending',
  },
  {
    school: 'soet',
    branch: 'bba',
    batch: '2025',
    paymentId: 'PAY12347',
    regNo: 'REG003',
    semFees: '45000',
    regFees: '4000',
    fine: '500',
    paymentMode: 'online',
    chequeNo: '',
    transactionId: 'TXN12345',
    bankName: 'ICICI',
    status: 'completed',
  },
  {
    school: 'som',
    branch: 'bba',
    batch: '2023',
    paymentId: 'PAY12348',
    regNo: 'REG004',
    semFees: '48000',
    regFees: '4500',
    fine: '0',
    paymentMode: 'cash',
    chequeNo: '',
    transactionId: '',
    bankName: '',
    status: 'completed',
  },
  {
    school: 'soet',
    branch: 'mba',
    batch: '2024',
    paymentId: 'PAY12349',
    regNo: 'REG005',
    semFees: '60000',
    regFees: '5500',
    fine: '0',
    paymentMode: 'cheque',
    chequeNo: 'CHQ54321',
    transactionId: '',
    bankName: 'Axis Bank',
    status: 'pending',
  }
];